free:
  limits:
    memberships:
      have:
        count: 1
        enforcement: hard
basic:
  price: standard
  image: "sparkles.png"
  limits:
    memberships:
      have:
        count: null
  prices:
    standard_monthly:
      amount: 900
      currency: USD
      duration: 1
      interval: month
      quantity: memberships
      highlight: true
      trial_days: 7
    basic_annual:
      amount: 9000
      currency: USD
      duration: 1
      interval: year
      quantity: memberships
      highlight: true
# pro:
#   price: pro_2022
#   image: "rocket.png"
#   limits:
#     memberships:
#       have:
#         count: 10
#         enforcement: soft
#     scaffolding/absolutely_abstract/creative_concepts:
#       have:
#         count: null
#   prices:
#     pro_monthly_2022:
#       amount: 10000
#       currency: USD
#       duration: 1
#       interval: month
#     pro_annual_2022:
#       amount: 100000
#       currency: USD
#       duration: 1
#       interval: year
